// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClO5QgQflnESMtSFTHrH2bhmDwJo85kOA',
    appId: '1:62319465023:web:8e485afb0fb70d067ade8a',
    messagingSenderId: '62319465023',
    projectId: 'bolchaal-8d81b',
    authDomain: 'bolchaal-8d81b.firebaseapp.com',
    storageBucket: 'bolchaal-8d81b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZZPxpTuPV5owxh981qVgmJldRi4XbAVg',
    appId: '1:62319465023:android:e2aaad55eed40a187ade8a',
    messagingSenderId: '62319465023',
    projectId: 'bolchaal-8d81b',
    storageBucket: 'bolchaal-8d81b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIupvlDCS2HMvZerjHsX_4FZpTGar_5UE',
    appId: '1:62319465023:ios:03c2201c5693d2ed7ade8a',
    messagingSenderId: '62319465023',
    projectId: 'bolchaal-8d81b',
    storageBucket: 'bolchaal-8d81b.appspot.com',
    androidClientId:
        '62319465023-m36uuolq9tu659g1nm75fo297skd5dfs.apps.googleusercontent.com',
    iosClientId:
        '62319465023-j68v9t8ovibs346vepf6h1h0a6bjtkpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolchaal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIupvlDCS2HMvZerjHsX_4FZpTGar_5UE',
    appId: '1:62319465023:ios:f1fcbb3db0cf49887ade8a',
    messagingSenderId: '62319465023',
    projectId: 'bolchaal-8d81b',
    storageBucket: 'bolchaal-8d81b.appspot.com',
    androidClientId:
        '62319465023-m36uuolq9tu659g1nm75fo297skd5dfs.apps.googleusercontent.com',
    iosClientId:
        '62319465023-6grd8q1ift7m56nhit6p7uplsuead7l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolchaal.RunnerTests',
  );
}
